SET DEPLIBS_DIR=c:\proj64_deplibs
SET GLEW_ROOT=d:\proj64_cmake

rd /s /q build

cmake -S . -B build ^
 -DCMAKE_PREFIX_PATH=%DEPLIBS_DIR% ^
 -DBoost_ROOT=%DEPLIBS_DIR%\boost_1_84_0 ^
 -DFFTW_ROOT=%DEPLIBS_DIR%\fftw-3.3.10 ^
 -DLCMS2_ROOT=%DEPLIBS_DIR%\lcms2-2.15 ^
 -DGLEW_ROOT=%DEPLIBS_DIR%\glew-2.1.0 ^
 -DBUILD_PYTHON_BINDINGS=OFF ^
 -DBUILD_PYTHON_MODULE=OFF ^
 -DBUILD_XPCJS_BINDINGS=ON ^
 -DCGAL_DO_NOT_WARN_ABOUT_CMAKE_BUILD_TYPE=TRUE ^
 -DCMAKE_BUILD_TYPE=Release
