name: 'Build UXP GUI posix'
description: 'Build UXP GUI posix'

inputs:
  basedir:
     description: 'base dir'
     required: true

outputs:
  artifact-path:
    description: 'built file'
    value: ${{ steps.create-artifact.outputs.artifact-path }}

runs:
  using: "composite"
  steps:
  - name: Install python2
    shell: bash
    env:
      SCCACHE_GHA_ENABLED: "true"
    run: |
      brew install pyenv zlib

      export PYENV_ROOT="$HOME/.pyenv"
      command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"

      env CC="sccache clang" CXX=="sccache clang++" LDFLAGS="-L$(brew --prefix zlib)/lib" CPPFLAGS="-I$(brew --prefix zlib)/include" PKG_CONFIG_PATH="$(brew --prefix zlib)/lib/pkgconfig" pyenv install 2.7.18
      pyenv global 2.7.18
      pyenv versions
      python --version

  - name: Build UXP GUI
    id: create-artifact
    shell: bash
    env:
      SCCACHE_GHA_ENABLED: "true"
      ARTIFACT_NAME: cuemol2_${{ runner.os }}_${{ runner.arch }}.tar.bz2
    run: |
      export PYENV_ROOT="$HOME/.pyenv"
      command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
      pyenv global 2.7.18

      cd ${GITHUB_WORKSPACE}
      which python
      python --version
      bash build_scripts/build_uxpgui_posix/run.sh ${{ inputs.basedir }} ${{ runner.os }} ${{ runner.arch }}

      ls -l ${GITHUB_WORKSPACE}/${ARTIFACT_NAME}
      echo "artifact-path=${GITHUB_WORKSPACE}/${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
