name: 'Build libcuemol2 posix'
description: 'Build libcuemol2 posix'

inputs:
  basedir:
     description: 'base dir'
     required: true

runs:
  using: "composite"
  steps:
  - name: Install prerequsites
    shell: bash
    run: |
      if [ ${{ runner.os }} = "macOS" ]; then
        brew install bison
        export PATH="/opt/homebrew/opt/bison/bin:$PATH"
      elif [ ${{ runner.os }} = "Linux" ]; then
        echo "XXX"
      else
        echo "unknown runner os: ${{ runner.os }}"
        exit 1
      fi
      bison --version

  - name: Install deplibs and build libcuemol2
    shell: bash
    env:
      SCCACHE_GHA_ENABLED: "true"
    run: |
      cd ${GITHUB_WORKSPACE}
      if [ ${{ runner.os }} = "macOS" ]; then
        export PATH="/opt/homebrew/opt/bison/bin:$PATH"
      fi
      bash build_scripts/build_libcuemol2_macos.sh ${{ inputs.basedir }} ${{ runner.os }} ${{ runner.arch }}
