name: 'Build libcuemol2 posix'
description: 'Build libcuemol2 posix'

inputs:
  basedir:
     description: 'base dir'
     required: true

runs:
  using: "composite"
  steps:
  - name: Install prerequsites
    shell: bash
    run: |
      brew install bison
      export PATH="/opt/homebrew/opt/bison/bin:$PATH"
      bison --version

  - name: Install deplibs and build libcuemol2
    shell: bash
    env:
      SCCACHE_GHA_ENABLED: "true"
    run: |
      cd ${GITHUB_WORKSPACE}
      export PATH="/opt/homebrew/opt/bison/bin:$PATH"
      bash build_scripts/build_libcuemol2_macos.sh ${{ inputs.basedir }} ${{ runner.arch }}
