name: Build and release

on:
  push:
    # branches-ignore:
    #   - '**'

###############################################

jobs:
  build_mac_arm64:
    name: "MacOS 14 arm64 clang"
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.4

    - name: Build libcuemol2
      uses: ./.github/actions/build_libcuemol2_posix

    - name: Build cuetty
      uses: ./.github/actions/build_cuetty_posix

    # - name: Upload artifact
    #   env:
    #     ARTIFACT_NAME: cuemol2_${{ runner.os }}_${{ runner.arch }}.tar.bz2
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: cuemol2_macos_arm64
    #     path: ${{ env.ARTIFACT_NAME }}
