name: Build and release

on:
  push:
    # branches-ignore:
    #   - '**'

###############################################

jobs:
  build_win_x64:
    name: "Windows intel msvc"
    runs-on: windows-2022
    steps:
    - name: Install prerequisite
      run: |
        cmake --version
        choco install -r wget winflexbison3
        Start-BitsTransfer -Source https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-3.4.exe -Destination ./MozillaBuildSetup.exe
        .\MozillaBuildSetup.exe /S | Out-Null
        dir C:\mozilla-build

    - uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Install deplibs and build libcuemol2
      shell: cmd
      run: |
        echo on
        cd %GITHUB_WORKSPACE%
        set HOME=%HOMEDRIVE%%HOMEPATH%
        cmd /c %GITHUB_WORKSPACE%\build_scripts\build_libcuemol2_win.bat %HOME%

    - name: Build cuetty
      shell: cmd
      run: |
        echo on
        cd %GITHUB_WORKSPACE%
        set HOME=%HOMEDRIVE%%HOMEPATH%
        cmd /c %GITHUB_WORKSPACE%\build_scripts\build_cuetty_win.bat %HOME%

    - name: Get repository dirname
      id: get-repos-dir
      shell: bash
      run: |
        set -eux
        REPOS_DIR=$(echo '${{ github.workspace }}' | sed 's/\\/\//g')
        echo "repos-dir=$REPOS_DIR" >> $GITHUB_OUTPUT
        HOMEPATH_UX=$(echo "$HOMEPATH" | sed 's/\\/\//g')
        echo "home-dir=$HOMEDRIVE$HOMEPATH_UX" >> $GITHUB_OUTPUT

    - name: Run mozilla build
      shell: cmd
      run: |
        echo on
        echo ${{ steps.get-repos-dir.outputs.repos-dir }}
        cmd /c C:\mozilla-build\start-shell.bat ${{ steps.get-repos-dir.outputs.repos-dir }}/build_scripts/build_uxpgui_win.sh ${{ steps.get-repos-dir.outputs.home-dir }}
