name: Build and release

on:
  push:
    # branches-ignore:
    #   - '**'

###############################################

jobs:
  build_posix:
    name: '${{ matrix.name }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            name: "MacOS 14 arm64 clang"
          - os: macos-12
            name: "MacOS 12 x64 clang"

    steps:
    - uses: actions/checkout@v4

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.4

    - name: Download deplibs
      uses: ./build_scripts/download_deplibs
      with:
        basedir: ${{ github.workspace }}/target

    - name: Build libcuemol2
      uses: ./build_scripts/build_libcuemol2_posix
      with:
        basedir: ${{ github.workspace }}/target

    - name: Build cuetty
      uses: ./build_scripts/build_cuetty_posix
      with:
        basedir: ${{ github.workspace }}/target

    - name: Check cuetty run
      shell: bash
      run: |
        set -eux
        BASEDIR=${{ github.workspace }}/target
        ls -la $BASEDIR/cuemol2/bin/cuetty
        $BASEDIR/cuemol2/bin/cuetty
        
    - name: Build UXP GUI
      id: build-artifact
      uses: ./build_scripts/build_uxpgui_posix
      with:
        basedir: ${{ github.workspace }}/target

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cuemol2_macos_arm64
        path: ${{ steps.build-artifact.outputs.artifact-path }}

###############################################

  release_build:
    needs: [build_posix]
    runs-on: ubuntu-latest
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: true
    - run: |
        ls -lR

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: artifacts/*
