name: Build test 2 (windows)

on:
  push:
    # branches-ignore:
    #   - '**'

###############################################

jobs:
  build_win_x64:
    name: "Windows intel msvc"
    runs-on: windows-2019

    steps:
    # - uses: actions/checkout@v4

    # - name: Add MSBuild to PATH
    #   uses: microsoft/setup-msbuild@v1.0.2

    - name: Install prerequisite
      run: |
        Start-BitsTransfer -Source https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-3.4.exe -Destination ./MozillaBuildSetup.exe
        .\MozillaBuildSetup.exe /S | Out-Null
        dir c:\
        
    # - name: Install prerequisite
    #   shell: cmd
    #   run: |
    #     choco install mozillabuild
    #     dir c:\

    - name: test1
      shell: bash
      run: |
        set -eux
        echo '${{ github.workspace }}' | sed 's/\\/\//g'

    - name: Run mozilla build
      shell: cmd
      run: |
        REM cmd /c C:/mozilla-build/start-shell.bat ${{ github.workspace }}/build_scripts/test_win1.sh
        REM cmd /c C:/mozilla-build/start-shell.bat /d/a/cuemol2/cuemol2/build_scripts/test_win1.sh
        cmd /c C:/mozilla-build/start-shell.bat pwd
        cmd /c C:/mozilla-build/start-shell.bat ls -la D:/a
        cmd /c C:/mozilla-build/start-shell.bat ls -la D:/a/cuemol2
        cmd /c C:/mozilla-build/start-shell.bat ls -la D:/a/cuemol2/cuemol2
