name: Build and release

on:
  push:
    branches-ignore:
      - '**'

###############################################

jobs:
  build_win_x64:
    name: "Windows intel msvc"
    runs-on: windows-2022
    steps:
    - name: Install prerequisite
      run: |
        cmake --version
        choco install -r wget winflexbison3
        Start-BitsTransfer -Source https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-3.4.exe -Destination ./MozillaBuildSetup.exe
        .\MozillaBuildSetup.exe /S | Out-Null
        dir c:\

    - uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Install deplibs and build libcuemol2
      shell: cmd
      run: |
        echo on
        cd %GITHUB_WORKSPACE%
        set HOME=%HOMEDRIVE%%HOMEPATH%
        cmd /c %GITHUB_WORKSPACE%\build_scripts\build_libcuemol2_win.bat %HOME%

    - name: Build cuetty
      shell: cmd
      run: |
        echo on
        cd %GITHUB_WORKSPACE%
        set HOME=%HOMEDRIVE%%HOMEPATH%
        cmd /c %GITHUB_WORKSPACE%\build_scripts\build_cuetty_win.bat %HOME%

    - name: Run mozilla build
      shell: cmd
      run: |
        cmd /c C:/mozilla-build/start-shell.bat D:/a/cuemol2/cuemol2/build_scripts/test_win1.sh

