name: Build and release

on:
  push:

###############################################

env:
  PYTHON_VERSION: 2.7

jobs:
  build_mac_arm64:
    name: "MacOS 14 arm64 clang"
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.4

    - name: Install deplibs and build libcuemol2
      shell: bash
      env:
        SCCACHE_GHA_ENABLED: "true"
      run: |
        cd ${GITHUB_WORKSPACE}
        bash build_scripts/build_libcuemol2_macos.sh $HOME ${{ runner.arch }}

    - name: Install python2
      shell: bash
      env:
        SCCACHE_GHA_ENABLED: "true"
      run: |
        brew install pyenv zlib autoconf@2.13

        export PYENV_ROOT="$HOME/.pyenv"
        command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"

        env CC="sccache clang" CXX=="sccache clang++" LDFLAGS="-L/opt/homebrew/opt/zlib/lib" CPPFLAGS="-I/opt/homebrew/opt/zlib/include" PKG_CONFIG_PATH="/opt/homebrew/opt/zlib/lib/pkgconfig" pyenv install 2.7.18
        pyenv global 2.7.18
        pyenv versions
        python --version

    - name: Build UXP GUI
      shell: bash
      env:
        SCCACHE_GHA_ENABLED: "true"
        ARTIFACT_NAME: cuemol2_${{ runner.os }}_${{ runner.arch }}.tar.bz2
      run: |
        export PYENV_ROOT="$HOME/.pyenv"
        command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        pyenv global 2.7.18

        cd ${GITHUB_WORKSPACE}
        which python
        python --version
        bash build_scripts/build_uxpgui_macos.sh $HOME ${{ runner.arch }}
        
        cd ${GITHUB_WORKSPACE}/

    - name: Upload artifact
      env:
        ARTIFACT_NAME: cuemol2_${{ runner.os }}_${{ runner.arch }}.tar.bz2
      uses: actions/upload-artifact@v4
      with:
        name: cuemol2_macos_arm64
        path: ${{ env.ARTIFACT_NAME }}

  # build_mac_intel:
  #   name: "MacOS 12 intel clang"
  #   runs-on: macos-12
  #   steps:
  #   - uses: actions/checkout@v4

  #   - name: Run sccache-cache
  #     uses: mozilla-actions/sccache-action@v0.0.4

  #   - name: Install deplibs and build libcuemol2
  #     shell: bash
  #     env:
  #       SCCACHE_GHA_ENABLED: "true"
  #     run: |
  #       sccache -s
  #       cd ${GITHUB_WORKSPACE}
  #       bash build_scripts/build_libcuemol2_macos.sh $HOME ${{ runner.arch }}

