name: Build and release

on:
  push:
    # branches-ignore:
    #   - '**'

env:
  mozbuild-cache-version: v1
  uxp-cache-version: v1
  libcuemol-cache-version: v1

###############################################

jobs:
  build_win_x64:
    name: "Windows intel msvc"
    runs-on: windows-2022
    # runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4

    - name: mozbuild cache
      uses: actions/cache@v4
      id: mozbuild-cache
      with:
        path: C:\mozilla-build\
        key: mozbuild-${{ env.mozbuild-cache-version }}
        restore-keys: |
          mozbuild-

    # - name: uxp cache
    #   uses: actions/cache@v4
    #   id: uxp-cache
    #   with:
    #     path: ${{ github.workspace }}\uxp_gui\platform
    #     key: uxp-${{ env.uxp-cache-version }}
    #     restore-keys: |
    #       uxp-

    - name: libcuemol cache
      uses: actions/cache@v4
      id: libcuemol-cache
      with:
        path: ${{ runner.temp }}\proj64_deplibs\cuemol2
        key: libcuemol-${{ env.libcuemol-cache-version }}
        restore-keys: |
          libcuemol-

    - name: Download/install uxp bin
      # if: steps.uxp-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -eux
        cd $GITHUB_WORKSPACE/uxp_gui
        wget --progress=dot:giga -c https://github.com/CueMol/uxp_release/actions/runs/9122708661/artifacts/1511942925
        ls -la
        unzip uxpbin_windows_x64.zip
        ls -la
        tar --use-compress-program "zstd -d" -xf uxpbin_windows_x64.tar.zst 
        ls -la

    - name: Install prerequisite
      run: |
        choco install -r wget winflexbison3

    - name: Install mozbuild
      if: steps.mozbuild-cache.outputs.cache-hit != 'true'
      run: |
        $mozilladir = "c:\mozilla-build"
        $src_url = "https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-3.4.exe"
        Start-BitsTransfer -Source $src_url -Destination ./MozillaBuildSetup.exe
        .\MozillaBuildSetup.exe /S | Out-Null
        dir $mozilladir

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Get repository dirname
      id: get-repos-dir
      shell: bash
      run: |
        set -eux
        REPOS_DIR=$(echo '${{ github.workspace }}' | sed 's/\\/\//g')
        echo "repos-dir=$REPOS_DIR" >> $GITHUB_OUTPUT
        HOMEPATH_UX=$(echo "$HOMEPATH" | sed 's/\\/\//g')
        echo "home-dir=$HOMEDRIVE$HOMEPATH_UX" >> $GITHUB_OUTPUT

    - name: Edit mozconfig
      shell: bash
      run: |
        set -eux
        cd $GITHUB_WORKSPACE
        # WIN32_REDIST_DIR=$(echo "${VCToolsRedistDir}x64\\Microsoft.VC142.CRT" | sed 's/\\/\//g')
        WIN32_REDIST_DIR=$(echo "${VCToolsRedistDir}x64\\Microsoft.VC143.CRT" | sed 's/\\/\//g')
        echo "$WIN32_REDIST_DIR"
        WIN_UCRT_REDIST_DIR=$(echo "${WindowsSdkDir}Redist\\${WindowsSDKLibVersion}ucrt\\DLLs\\x64" | sed 's/\\/\//g')
        echo "$WIN_UCRT_REDIST_DIR"

        BASEDIR=$(echo '${{ runner.temp }}' | sed 's/\\/\//g')
        DEPLIBS_DIR=$BASEDIR/proj64_deplibs
        BUNDLE_DIR=$BASEDIR/cuemol2_bundle

        BOOST_DIR=$DEPLIBS_DIR/boost_1_84_0/include/boost-1_84
        LIBDIR=$DEPLIBS_DIR/boost_1_84_0/lib
        CUEMOL_DIR=$DEPLIBS_DIR/cuemol2
        
        cd uxp_gui
        sed "s!@WIN32_REDIST_DIR@!$WIN32_REDIST_DIR!g" $GITHUB_WORKSPACE/build_scripts/mozconfig_win \
        | sed "s!@WIN_UCRT_REDIST_DIR@!$WIN_UCRT_REDIST_DIR!g" \
        | sed "s!@CUEMOL_BUNDLE@!$BUNDLE_DIR!g" \
        | sed "s!@CUEMOL_DIR@!$CUEMOL_DIR!g" \
        | sed "s!@BOOST_DIR@!$BOOST_DIR!g" \
        | sed "s!@DEPLIBS_DIR@!$LIBDIR!g" > .mozconfig

        cat .mozconfig

    - name: Download/install deplibs
      shell: bash
      run: |
        set -eux
        TEMP_DIR=$(echo '${{ runner.temp }}' | sed 's/\\/\//g')
        cd $GITHUB_WORKSPACE
        bash build_scripts/download_deplibs/run_windows.sh $TEMP_DIR
        
    - name: Build libcuemol2
      if: steps.libcuemol-cache.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        echo on
        cd %GITHUB_WORKSPACE%
        SET DEPLIBS_DIR=${{ runner.temp }}\proj64_deplibs
        dir %DEPLIBS_DIR%
        cmd /c %GITHUB_WORKSPACE%\build_scripts\build_libcuemol2_win.bat ${{ runner.temp }}

    - name: Build cuetty
      shell: cmd
      run: |
        echo on
        cd %GITHUB_WORKSPACE%
        set HOME=%HOMEDRIVE%%HOMEPATH%
        cmd /c %GITHUB_WORKSPACE%\build_scripts\build_cuetty_win.bat ${{ runner.temp }}

    - name: Run mozilla build
      shell: cmd
      run: |
        echo on
        echo ${{ steps.get-repos-dir.outputs.repos-dir }}
        cmd /c C:\mozilla-build\start-shell.bat ${{ steps.get-repos-dir.outputs.repos-dir }}/build_scripts/build_uxpgui_win.sh ${{ runner.temp }}
